import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import CompetitionMatchPreview from "../components/CompetitionMatchPreview";
import CompetitionParticipants from "../components/CompetitionParticipants";
import CompetitionStandingsPreview from "../components/CompetitionStandingsPreview";
import CompetitionStatusBadge from "../components/CompetitionStatusBadge";
import { getCompetitionById, getCompetitionRecentResults, getCompetitionStandings, getCompetitionUpcomingMatches } from "../services/competitionService";
import { formatCompetitionRange, formatLabel } from "../utils/competitionFormatters";

const CompetitionDetailsPage = () => {
  const { competitionId } = useParams(); const [state, setState] = useState({ status: "loading", competition: null, standings: [], results: [], fixtures: [] });
  useEffect(() => { let active = true; Promise.all([getCompetitionById(competitionId), getCompetitionStandings(competitionId), getCompetitionRecentResults(competitionId), getCompetitionUpcomingMatches(competitionId)]).then(([competition, standings, results, fixtures]) => active && setState({ status: "success", competition, standings: standings.slice(0, 5), results, fixtures })).catch(() => active && setState({ status: "error", competition: null, standings: [], results: [], fixtures: [] })); return () => { active = false; }; }, [competitionId]);
  if (state.status !== "success") return <main className="min-h-screen bg-[#011427] pt-32 text-center text-white/60">{state.status === "error" ? "Competition details are unavailable." : "Loading competition details…"}</main>;
  const competition = state.competition; const overview = [["FORMAT", formatLabel(competition.format)], ["DIVISION", formatLabel(competition.gender)], ["COMPETITION DATES", formatCompetitionRange(competition.competition_start_date, competition.competition_end_date)], ["REGISTRATION WINDOW", formatCompetitionRange(competition.registration_start_date, competition.registration_end_date)], ["SQUAD SIZE", competition.squad_size ? `${competition.squad_size} players` : null], ["MAXIMUM TEAMS", competition.max_teams ? `${competition.max_teams} teams` : null]];
  return <main className="min-h-screen bg-[#011427] pb-20 pt-32 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><Link to="/competitions" className="text-xs font-bold text-[#EEC058] hover:text-[#ffad9f]">← ALL COMPETITIONS</Link><section className="relative mt-6 overflow-hidden rounded-xl border border-[#EEC058]/25 bg-[linear-gradient(125deg,#17334a,#0B1D2F_60%,#07192a)] p-6 sm:p-10"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-[11px] font-bold tracking-[.2em] text-[#EEC058]">HUNZA PREMIER LEAGUE</p><h1 className="mt-3 text-4xl font-extrabold uppercase sm:text-5xl">{competition.name}</h1>{competition.season && <Link to={`/seasons/${competition.season_id}`} className="mt-4 inline-flex text-sm font-bold text-[#ffad9f] hover:text-[#EEC058]">{competition.season.name} season →</Link>}</div><CompetitionStatusBadge status={competition.status} /></div>{competition.description && <p className="mt-7 max-w-3xl text-sm leading-7 text-white/65">{competition.description}</p>}<Link to={`/competitions/${competitionId}/register`} className="mt-6 inline-flex rounded bg-[#FF553D] px-4 py-3 text-xs font-bold text-white hover:bg-[#ff6f5c]">REGISTER A TEAM</Link></section><section className="mt-16"><p className="text-[11px] font-bold tracking-[.18em] text-[#EEC058]">COMPETITION OVERVIEW</p><div className="mt-7 grid gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{overview.filter(([, value]) => value).map(([label, value]) => <div key={label} className="bg-[#0B1D2F] p-5"><p className="text-[10px] font-bold tracking-[.14em] text-white/45">{label}</p><p className="mt-2 text-sm font-semibold">{value}</p></div>)}</div></section><CompetitionParticipants competitionId={competitionId} /><section className="mt-16"><p className="text-[11px] font-bold tracking-[.18em] text-[#EEC058]">STANDINGS PREVIEW</p><h2 className="mt-3 text-2xl font-extrabold">League table</h2><div className="mt-7">{state.standings.length ? <CompetitionStandingsPreview standings={state.standings} /> : <p className="rounded-xl border border-white/10 p-6 text-sm text-white/55">No standings are available for this competition yet.</p>}</div></section><div className="mt-16 grid gap-12 lg:grid-cols-2"><section><h2 className="text-2xl font-extrabold">Completed matches</h2><div className="mt-7 space-y-4">{state.results.length ? state.results.map((match) => <CompetitionMatchPreview key={match.match_id} match={match} type="result" />) : <p className="text-sm text-white/55">No completed matches are available yet.</p>}</div></section><section><h2 className="text-2xl font-extrabold">Next matches</h2><div className="mt-7 space-y-4">{state.fixtures.length ? state.fixtures.map((match) => <CompetitionMatchPreview key={match.match_id} match={match} type="fixture" />) : <p className="text-sm text-white/55">No upcoming fixtures are scheduled.</p>}</div></section></div></div></main>;
};
export default CompetitionDetailsPage;
