import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import RefereeAvatar from "../components/RefereeAvatar";
import { getReferees } from "../services/refereeService";

const RefereesPage = () => {
  const [state, setState] = useState({ status: "loading", items: [], pagination: {} });
  const [q, setQ] = useState("");
  const [page, setPage] = useState(1);
  const load = async () => { setState((previous) => ({ ...previous, status: "loading" })); try { const result = await getReferees({ q, page, limit: 12 }); setState({ status: "success", items: result?.data || [], pagination: result?.pagination || {} }); } catch { setState((previous) => ({ ...previous, status: "error" })); } };
  useEffect(() => { let active = true; const timer = setTimeout(async () => { try { const result = await getReferees({ q, page, limit: 12 }); if (active) setState({ status: "success", items: result?.data || [], pagination: result?.pagination || {} }); } catch { if (active) setState((previous) => ({ ...previous, status: "error" })); } }, 220); return () => { active = false; clearTimeout(timer); }; }, [q, page]);
  return <main className="min-h-screen bg-[#011427] pb-20 pt-20 text-white"><header className="border-b border-white/10 bg-[#07192a]"><div className="mx-auto max-w-7xl px-5 py-12 sm:px-6 lg:px-8"><p className="text-xs font-bold tracking-[.2em] text-[#EEC058]">HUNZA PREMIER LEAGUE</p><h1 className="mt-3 text-4xl font-extrabold text-[#ffad9f]">REFEREES</h1><p className="mt-3 text-sm text-white/60">Meet the officials responsible for matches across the Hunza Premier League.</p></div></header><section className="mx-auto max-w-7xl px-5 py-8 sm:px-6 lg:px-8"><input value={q} onChange={(event) => { setQ(event.target.value); setPage(1); }} placeholder="Search referees" className="h-11 w-full max-w-md rounded-md border border-white/15 bg-[#0B1D2F] px-3 text-sm outline-none focus:border-[#FF553D]" />{state.status === "loading" && <p className="mt-6 text-sm text-white/50">Loading referees…</p>}{state.status === "error" && <div className="mt-6 text-sm text-red-200">Unable to load referees. <button onClick={load} className="font-bold underline">TRY AGAIN</button></div>}{state.status === "success" && <><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{state.items.map((referee) => <article key={referee.referee_id} className="flex gap-4 rounded-xl border border-white/10 bg-[#0B1D2F] p-5"><RefereeAvatar referee={referee} /><div className="min-w-0"><h2 className="truncate font-extrabold">{referee.name}</h2><p className="mt-1 text-sm text-white/55">{[referee.city, referee.region].filter(Boolean).join(", ") || "Hunza Premier League"}</p><p className="mt-2 text-xs text-[#EEC058]">{referee.matches_officiated} ASSIGNMENTS</p><Link to={`/referees/${referee.referee_id}`} className="mt-4 inline-block text-xs font-bold text-[#ffad9f]">VIEW PROFILE →</Link></div></article>)}</div>{!state.items.length && <p className="mt-6 rounded-xl border border-white/10 p-6 text-sm text-white/55">{q ? "No referees match your search." : "No active referees are available."}</p>}<div className="mt-8 flex gap-3"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded border border-white/20 px-3 py-2 text-xs disabled:opacity-40">PREVIOUS</button><button disabled={!state.pagination.total_pages || page >= state.pagination.total_pages} onClick={() => setPage(page + 1)} className="rounded border border-white/20 px-3 py-2 text-xs disabled:opacity-40">NEXT</button></div></>}</section></main>;
};
export default RefereesPage;
