export const AUDIT_ACTIONS = {
  USER_ROLE_UPDATED: "USER_ROLE_UPDATED",

  CLUB_CREATED: "CLUB_CREATED",
  CLUB_UPDATED: "CLUB_UPDATED",
  CLUB_DEACTIVATED: "CLUB_DEACTIVATED",
  CLUB_ACTIVATED: "CLUB_ACTIVATED",
  CLUB_OWNERSHIP_TRANSFERRED:
    "CLUB_OWNERSHIP_TRANSFERRED",

  TEAM_CREATED: "TEAM_CREATED",
  TEAM_UPDATED: "TEAM_UPDATED",
  TEAM_DEACTIVATED: "TEAM_DEACTIVATED",
  TEAM_ACTIVATED: "TEAM_ACTIVATED",
  TEAM_OWNERSHIP_TRANSFERRED:
    "TEAM_OWNERSHIP_TRANSFERRED",

  VENUE_CREATED: "VENUE_CREATED",
  VENUE_UPDATED: "VENUE_UPDATED",

  PLAYER_CREATED: "PLAYER_CREATED",
};